# Generated by Django 5.0.4 on 2024-10-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0002_currentsessionclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentsessionclient',
            old_name='firstname',
            new_name='current_session_client',
        ),
    ]
