# Generated by Django 5.0.4 on 2024-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0003_rename_firstname_currentsessionclient_current_session_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclientreg',
            name='uniq_number',
            field=models.CharField(default=78, max_length=40, unique=True),
        ),
    ]
