# Generated by Django 5.0.4 on 2024-10-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0004_newclientreg_uniq_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclientreg',
            name='uniq_number',
            field=models.CharField(default=594, max_length=40),
        ),
    ]
