# Generated by Django 5.0.4 on 2024-10-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0006_alter_newclientreg_uniq_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newclientreg',
            name='uniq_number',
        ),
    ]
