# Generated by Django 5.0.4 on 2024-10-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0007_remove_newclientreg_uniq_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsessionclient',
            name='current_session_client_email',
            field=models.CharField(default='No data', max_length=40),
        ),
    ]
