# Generated by Django 5.0.4 on 2024-10-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0008_currentsessionclient_current_session_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclientreg',
            name='password_confirmation',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
