# Generated by Django 5.0.4 on 2024-10-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0010_newclientreg_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsessionclient',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
