# Generated by Django 5.0.4 on 2024-10-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0013_existedclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='existedclient',
            old_name='existed_discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='existedclient',
            old_name='existed_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='existedclient',
            old_name='existed_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='existedclient',
            old_name='existed_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='existedclient',
            old_name='existed_password',
            new_name='password',
        ),
    ]
