# Generated by Django 5.0.4 on 2024-10-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0014_rename_existed_discount_existedclient_discount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistedClient',
        ),
    ]
