# Generated by Django 5.0.4 on 2024-10-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0015_delete_existedclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=40)),
                ('client_id', models.CharField(max_length=40)),
                ('food_name', models.CharField(max_length=40)),
                ('food_count', models.IntegerField()),
            ],
        ),
    ]
