# Generated by Django 5.0.4 on 2024-10-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0017_clientsorders_food_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsorders',
            name='food_count',
        ),
        migrations.AddField(
            model_name='clientsorders',
            name='food_amount',
            field=models.IntegerField(default=1),
        ),
    ]
