# Generated by Django 5.0.4 on 2024-10-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0018_remove_clientsorders_food_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsorders',
            old_name='client_id',
            new_name='client_email',
        ),
    ]
