# Generated by Django 5.0.4 on 2024-10-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0019_rename_client_id_clientsorders_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsorders',
            name='food_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientsorders',
            name='food_price',
            field=models.IntegerField(),
        ),
    ]
