# Generated by Django 5.0.4 on 2024-10-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0020_alter_clientsorders_food_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclientreg',
            name='firstname',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
