# Generated by Django 5.0.4 on 2024-10-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0022_alter_newclientreg_discount_alter_newclientreg_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsorders',
            name='client_email',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='clientsorders',
            name='client_name',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='clientsorders',
            name='food_amount',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='clientsorders',
            name='food_name',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='clientsorders',
            name='food_price',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='currentsessionclient',
            name='current_session_client_discount',
            field=models.IntegerField(default=1),
        ),
    ]
