# Generated by Django 5.0.4 on 2024-10-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0023_alter_clientsorders_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsorders',
            name='client_email',
            field=models.CharField(default='No data', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientsorders',
            name='client_name',
            field=models.CharField(default='No data', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientsorders',
            name='food_name',
            field=models.CharField(default='No data', max_length=40),
        ),
    ]
