# Generated by Django 5.0.9 on 2024-11-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoGraduateApp', '0026_alter_newclientreg_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsorders',
            name='food_page_path',
            field=models.CharField(default='No data', max_length=40),
        ),
    ]
